Promo.UI/Controllers/PromotionController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Promo.Model.Models;
using Promo.BusinessLogic.Promotions;
using System.Web;
using System.IO;
using Promo.Model.ViewModels;
using Promo.BusinessLogic.Errors;
using Promo.Helpers.Mappers;
using System;

namespace Promo.UI.Controllers
{
    [Authorize]
    public class PromotionController : Controller
    {
        private PromotionManager _promotionManager = new PromotionManager();
        private readonly ErrorManager _errorManager = new ErrorManager();
        private readonly ErrorMapper _errorMapper = new ErrorMapper();

        // GET: Promotion
        public ActionResult Index()
        {
            try
            {
                return View(_promotionManager.GetAllPromotions());
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Promotion/Details/5
        public ActionResult Details(int? promotionId)
        {
            try
            {
                if (promotionId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Promotion promotion = _promotionManager.GetPromotion(promotionId);
                if (promotion == null)
                {
                    return HttpNotFound();
                }
                return View(promotion);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Promotion/Create
        public ActionResult Create()
        {
            try
            {
                return View(_promotionManager.GetEmptyPromotion());
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // POST: Promotion/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PromotionViewModel promotionViewModel, HttpPostedFileBase file)
        {
            try
            {
                var promotion = promotionViewModel.Promotion;
                if (ModelState.IsValid)
                {
                    byte[] image = null;
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        string path;
                        if (fileName != null)
                        {
                            path = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                            file.SaveAs(path);
                            image = System.IO.File.ReadAllBytes(path);
                            System.IO.File.Delete(path);

                        }

                    }
                    promotion.Image = image;
                    _promotionManager.AddPromotion(promotion);
                    if (promotion.PromotionId != 0)
                    {
                        _promotionManager.AddPromotionBrands(promotion.PromotionId, promotionViewModel.BrandIds);
                        _promotionManager.AddPromotionStores(promotion.PromotionId, promotionViewModel.StoreIds);
                    }
                    return RedirectToAction("Index");
                }

                return View(promotion);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Promotion/Edit/5
        public ActionResult Edit(int? promotionId)
        {
            try
            {
                if (promotionId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var promotion = _promotionManager.GetPromotionToEdit(promotionId);
                if (promotion == null)
                {
                    return HttpNotFound();
                }
                return View(promotion);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // POST: Promotion/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( PromotionViewModel promotionViewModel)
        {
            try
            {
                var promotion = promotionViewModel.Promotion;
                if (ModelState.IsValid)
                {
                    byte[] image = null;

                    if (promotionViewModel.File != null && promotionViewModel.File.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(promotionViewModel.File.FileName);
                        string path;
                        if (fileName != null)
                        {
                            path = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                            promotionViewModel.File.SaveAs(path);
                            image = System.IO.File.ReadAllBytes(path);
                            System.IO.File.Delete(path);
                        }
                    }
                    promotion.Image = image;
                    _promotionManager.EditPromotion(promotion);

                    _promotionManager.DeletePromotionBrands(promotion.PromotionId);
                    _promotionManager.AddPromotionBrands(promotion.PromotionId, promotionViewModel.BrandIds);

                    _promotionManager.DeletePromotionStores(promotion.PromotionId);
                    _promotionManager.AddPromotionStores(promotion.PromotionId, promotionViewModel.StoreIds);

                    return RedirectToAction("Index");
                }
                return View(promotion);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Promo.UI/Views/Promotion/Create.cshtml
@model Promo.Model.ViewModels.PromotionViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Promotion", FormMethod.Post,
                                                    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Promotion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Promotion.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Promotion.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.DropDownListFor(x => x.Promotion.CompanyId, Model.Companies, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Promotion.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.Promotion.CountryId, Model.Countries, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Promotion.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.Promotion.CompanyId, Model.Categories, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Promotion.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Promotion.StartDate, new { htmlAttributes = new { @class = "form-control date" } })
                @Html.ValidationMessageFor(model => model.Promotion.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Promotion.EndDate, new { htmlAttributes = new { @class = "form-control date" } })
                @Html.ValidationMessageFor(model => model.Promotion.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.File, new { type = "file", htmlAttributes = new { @class = "form-control date" } })
                @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.Coupon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Promotion.Coupon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Promotion.Coupon, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class = "control-label col-md-2">Brands</label>
            <div class="col-md-10">
                <select class="js-brands-data-array form-control" name="BrandIds[]" id="BrandIds"></select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Stores</label>
            <div class="col-md-10">
                <select class="js-stores-data-array form-control" name="StoreIds[]" id="StoreIds"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customval")
    @Scripts.Render("~/Scripts/select2.js")
    @Scripts.Render("~/bundles/promotion")
}

Promo.UI/Views/Promotion/Delete.cshtml
@model Promo.Model.Models.Promotion

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Promotion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Promo.UI/Views/Promotion/Details.cshtml
@model Promo.Model.Models.Promotion

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Promotion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PromotionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Promo.UI/Views/Promotion/Edit.cshtml
@model Promo.Model.ViewModels.PromotionViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Promotion", FormMethod.Post,
                                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Promotion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Promotion.PromotionId)

        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Promotion.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Promotion.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.Promotion.CompanyId, Model.Companies, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Promotion.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.Promotion.CountryId, Model.Countries, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Promotion.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.Promotion.CategoryId, Model.Categories, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Promotion.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Promotion.StartDate, new { htmlAttributes = new { @class = "form-control date" } })
                @Html.ValidationMessageFor(model => model.Promotion.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Promotion.EndDate, new { htmlAttributes = new { @class = "form-control date" } })
                @Html.ValidationMessageFor(model => model.Promotion.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.File, new { type = "file", htmlAttributes = new { @class = "form-control date" } })
                @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Promotion.Coupon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Promotion.Coupon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Promotion.Coupon, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class = "control-label col-md-2">Brands</label>
            <div class="col-md-10">
                <select class="js-brands-data-array form-control" name="BrandIds[]" id="BrandIds"></select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Stores</label>
            <div class="col-md-10">
                <select class="js-stores-data-array form-control" name="StoreIds[]" id="StoreIds"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/customval")
    @Scripts.Render("~/Scripts/select2.js")
    @Scripts.Render("~/bundles/promotion")
<script type="text/javascript">
    $(document).ready(function () {
        $("#BrandIds").val("1");
    });
    </script>
}

Promo.UI/Views/Promotion/Index.cshtml
@model IEnumerable<Promo.Model.Models.Promotion>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { promotionId = item.PromotionId }) |
            @Html.ActionLink("Details", "Details", new { promotionId = item.PromotionId }) |
            @Html.ActionLink("Delete", "Delete", new { promotionId = item.PromotionId })
        </td>
    </tr>
}

</table>