Promo.UI/Controllers/BrandController.cs
using System.Net;
using System.Web.Mvc;
using Promo.Model.Models;
using Promo.BusinessLogic.Brands;
using System.Web;
using System.IO;
using Promo.BusinessLogic.Errors;
using Promo.Helpers.Mappers;
using System;

namespace Promo.UI.Controllers
{
    [Authorize]
    public class BrandController : Controller
    {
        private BrandManager _brandManager = new BrandManager();
        private readonly ErrorManager _errorManager = new ErrorManager();
        private readonly ErrorMapper _errorMapper = new ErrorMapper();
        // GET: Brands
        public ActionResult Index()
        {
            try
            {
                return View(_brandManager.GetAllBrands());
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
            
        }

        // GET: Brands/Details/5
        public ActionResult Details(int? brandId)
        {
            try
            {
                if (brandId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Brand brand = _brandManager.GetBrand(brandId);
                if (brand == null)
                {
                    return HttpNotFound();
                }
                return View(brand);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
            
        }

        // GET: Brands/Create
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
            
        }

        // POST: Brands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Brand brand, HttpPostedFileBase file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    byte[] image = null;
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        string path;
                        if (fileName != null)
                        {
                            path = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                            file.SaveAs(path);
                            image = System.IO.File.ReadAllBytes(path);
                            System.IO.File.Delete(path);

                        }

                    }
                    brand.Image = image;
                    _brandManager.AddBrand(brand);
                    return RedirectToAction("Index");
                }

                return View(brand);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Brands/Edit/5
        public ActionResult Edit(int? brandId)
        {
            try
            {
                if (brandId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Brand brand = _brandManager.GetBrand(brandId);
                if (brand == null)
                {
                    return HttpNotFound();
                }
                return View(brand);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Brand brand, HttpPostedFileBase file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    byte[] image = null;
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        string path;
                        if (fileName != null)
                        {
                            path = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                            file.SaveAs(path);
                            image = System.IO.File.ReadAllBytes(path);
                            System.IO.File.Delete(path);

                        }

                    }
                    brand.Image = image;
                    _brandManager.EditBrand(brand);
                    return RedirectToAction("Index");
                }
                return View(brand);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Promo.UI/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Promo.DataLayer;
using Promo.Model.Models;
using Promo.BusinessLogic.Companies;
using Promo.BusinessLogic.Errors;
using Promo.Helpers.Mappers;

namespace Promo.UI.Controllers
{
    [Authorize]
    public class CompanyController : Controller
    {
        private CompanyManager _companyManager = new CompanyManager();
        private readonly ErrorManager _errorManager = new ErrorManager();
        private readonly ErrorMapper _errorMapper = new ErrorMapper();

        // GET: Company
        public ActionResult Index()
        {
            try
            {
                return View(_companyManager.GetAllCompanies());
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
            
        }

        // GET: Company/Details/5
        public ActionResult Details(int? companyId)
        {
            try
            {
                if (companyId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Company company = _companyManager.GetCompany(companyId);
                if (company == null)
                {
                    return HttpNotFound();
                }
                return View(company);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
            
        }

        // GET: Company/Create
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
            
        }

        // POST: Company/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompanyId,Name")] Company company)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _companyManager.AddCompany(company);
                    return RedirectToAction("Index");
                }

                return View(company);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Company/Edit/5
        public ActionResult Edit(int? companyId)
        {
            try
            {
                if (companyId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Company company = _companyManager.GetCompany(companyId);
                if (company == null)
                {
                    return HttpNotFound();
                }
                return View(company);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
            
        }

        // POST: Company/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanyId,Name")] Company company)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _companyManager.EditCompany(company);
                    return RedirectToAction("Index");
                }
                return View(company);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
            
        }

    }
}

Promo.UI/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Promo.DataLayer;
using Promo.Model.Models;
using Promo.BusinessLogic.Stores;
using Promo.Model.ViewModels;
using Promo.BusinessLogic.Errors;
using Promo.Helpers.Mappers;

namespace Promo.UI.Controllers
{
    public class StoreController : Controller
    {
        private readonly StoreManager _storeManager = new StoreManager();
        private readonly ErrorManager _errorManager = new ErrorManager();
        private readonly ErrorMapper _errorMapper = new ErrorMapper();
        // GET: Store
        public ActionResult Index()
        {
            try
            {
                return View(_storeManager.GetAllStores());
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Store/Details/5
        public ActionResult Details(int? storeId)
        {
            try
            {
                if (storeId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Store store = _storeManager.GetStore(storeId);
                if (store == null)
                {
                    return HttpNotFound();
                }
                return View(store);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Store/Create
        public ActionResult Create()
        {
            try
            {
                return View(_storeManager.GetEmptyStore());
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // POST: Store/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StoreId,Name,Location,CompanyId")] Store store)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _storeManager.AddStore(store);
                    return RedirectToAction("Index");
                }

                return View(store);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Store/Edit/5
        public ActionResult Edit(int? storeId)
        {
            try
            {
                if (storeId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                StoreViewModel storeViewModel = _storeManager.GetPromotionToEdit(storeId);
                if (storeViewModel == null)
                {
                    return HttpNotFound();
                }
                return View(storeViewModel);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }

        // POST: Store/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StoreId,Name,Location,CompanyId")] Store store)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _storeManager.EditStore(store);
                    return RedirectToAction("Index");
                }
                return View(store);
            }
            catch (Exception ex)
            {
                var url = "";
                if (Request.Url != null)
                {
                    url = Request.Url.AbsoluteUri;
                }
                _errorManager.Log(_errorMapper.MapError(ex, url));
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Promo.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Companies", "Index", "Company")</li>
                    <li>@Html.ActionLink("Brands", "Index", "Brand")</li>
                    <li>@Html.ActionLink("Stores", "Index", "Store")</li>
                    <li>@Html.ActionLink("Countries", "Index", "Country")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Promotions", "Index", "Promotion")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Promo.UI/Views/Shared/_PageLayout.cshtml
<!DOCTYPE HTML>

<html>
<head>
    <title>Multiverse by HTML5 UP</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <!--[if lte IE 8]><script src="/scripts/multiverse/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="/content/themes/multiverse/css/main.css" />
    <!--[if lte IE 9]><link rel="stylesheet" href="/content/themes/multiverse/css/ie9.css" /><![endif]-->
    <!--[if lte IE 8]><link rel="stylesheet" href="/content/themes/multiverse/css/ie8.css" /><![endif]-->
</head>
<body>
    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Header -->
        <header id="header">
            <img src="~/Content/themes/multiverse/images/razprodaje-logo.png" />
            <div class="menu-toggle">
                <span class="menu-toggle-hamburger"></span>
            </div>
            <nav class="the-menu">
                <ul class="main-menu">
                    <li><a href="/categories" title="Kategorije">Kategorije</a>
                        @Html.Action("GetAllActiveCategories", "Category")
                        <ul>
                            <li><a href="/categories" title="Kategorije">Obleke</a></li>
                            <li><a href="/categories" title="Kategorije">Obutev</a></li>
                            <li><a href="/categories" title="Kategorije">Živila</a></li>
                            <li><a href="/categories" title="Kategorije">Tehnika</a></li>
                            <li><a href="/categories" title="Kategorije">Za živali</a></li>
                            <li><a href="/categories" title="Kategorije">Igrače</a></li>
                            <li><a href="/categories" title="Kategorije">Drogerija</a></li>
                        </ul>
                    </li>
                    <li><a href="/catalogs" title="Katalogi">Katalogi</a></li>
                    <li><a href="/brands" title="Blagovne znamke">Blagovne znamke</a></li>
                </ul>
                <form action="/search" method="get">
                    <input type="text" name="q" value="" placeholder="Search...">
                </form>
            </nav>
        </header>

        <!-- Main -->
        <div id="main">
            @RenderBody()
        </div>

        <!-- Footer -->
        <footer id="footer" class="panel">
            <div class="inner split">
                <div>
                    <section>
                        <h2>Magna feugiat sed adipiscing</h2>
                        <p>Nulla consequat, ex ut suscipit rutrum, mi dolor tincidunt erat, et scelerisque turpis ipsum eget quis orci mattis aliquet. Maecenas fringilla et ante at lorem et ipsum. Dolor nulla eu bibendum sapien. Donec non pharetra dui. Nulla consequat, ex ut suscipit rutrum, mi dolor tincidunt erat, et scelerisque turpis ipsum.</p>
                    </section>
                    <section>
                        <h2>Follow me on ...</h2>
                        <ul class="icons">
                            <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                            <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                            <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
                            <li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
                            <li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
                            <li><a href="#" class="icon fa-linkedin"><span class="label">LinkedIn</span></a></li>
                        </ul>
                    </section>
                    <p class="copyright">
                        &copy; Unttled. Design: <a href="http://html5up.net">HTML5 UP</a>.
                    </p>
                </div>
                <div>
                    <section>
                        <h2>Get in touch</h2>
                        <form method="post" action="#">
                            <div class="field half first">
                                <input type="text" name="name" id="name" placeholder="Name" />
                            </div>
                            <div class="field half">
                                <input type="text" name="email" id="email" placeholder="Email" />
                            </div>
                            <div class="field">
                                <textarea name="message" id="message" rows="4" placeholder="Message"></textarea>
                            </div>
                            <ul class="actions">
                                <li><input type="submit" value="Send" class="special" /></li>
                                <li><input type="reset" value="Reset" /></li>
                            </ul>
                        </form>
                    </section>
                </div>
            </div>
        </footer>

    </div>

    <!-- Scripts -->
    <script src="/scripts/multiverse/js/jquery.min.js"></script>
    <script src="/scripts/multiverse/js/jquery.poptrox.min.js"></script>
    <script src="/scripts/multiverse/js/skel.min.js"></script>
    <script src="/scripts/multiverse/js/util.js"></script>
    <!--[if lte IE 8]><script src="/scripts/multiverse/js/ie/respond.min.js"></script><![endif]-->
    <script src="/scripts/multiverse/js/main.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".menu-toggle").click(function () {
                $(this).toggleClass("on"), $(".the-menu").toggleClass("on")
            }
        );
        });
    </script>
</body>
</html>

Promo.UI/Views/Shared/_SiteLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_SiteLayout</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>